version: "3.8"
services:
    postgres:
        build:
            dockerfile: ./Dockerfile
            context: ./postgres
        ports:
            - 5432:5432
    web:
        build: .
        depends_on:
            - postgres
        ports:
            - 80:80